apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    app: nginx
    scope: demo
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        scope: demo
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
