apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy-service
  labels:
    app: nginx
    role: demo
spec:
  selector:
    app: nginx
    role: demo
  ports:
    - port: 80
      name: reverse-http-port
  type: LoadBalancer
  loadBalancerIP: <STATIC-IP-FROM-GOOGLE>
